<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="_0" nsURI="http://release.niem.gov/niem/codes/census_uscounty/3.0/"
    nsPrefix="_0">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="County codes from US Census and ANSI. &#xA;Publication: INCITS 31:2009; &#xA;Version: 2009; &#xA;http://www.census.gov/geo/www/ansi/download.html"/>
  </eAnnotations>
  <eAnnotations source="http://release.niem.gov/niem/conformanceTargets/3.0/">
    <details key="conformanceTargets" value="http://reference.niem.gov/niem/specification/naming-and-design-rules/3.0/#ReferenceSchemaDocument"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="USCountyCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for US county codes."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="USCountyCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="_1" literal="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="FL - Alachua County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_10" value="50" literal="10">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AS - Eastern District"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_100" value="53" literal="100">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MP - Rota Municipality"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_101" value="55" literal="101">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="OH - Marion County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_103" value="86" literal="103">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Effingham County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_105" value="117" literal="105">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="SD - Perkins County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_107" value="149" literal="107">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AL - Pickens County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_109" value="179" literal="109">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="PA - Snyder County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_11" value="209" literal="11">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MD - Caroline County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_110" value="256" literal="110">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Juneau City and Borough"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_111" value="258" literal="111">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AR - Poinsett County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_113" value="287" literal="113">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Madison County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_115" value="315" literal="115">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="SD - Spink County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_117" value="343" literal="117">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="CO - Summit County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_119" value="370" literal="119">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MO - McDonald County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_12" value="397" literal="12">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AZ - La Paz County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_120" value="398" literal="120">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MP - Tinian Municipality"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_121" value="399" literal="121">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="IL - Marion County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_122" value="426" literal="122">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Kenai Peninsula Borough"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_123" value="427" literal="123">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="SD - Tripp County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_125" value="453" literal="125">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Glascock County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_127" value="479" literal="127">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="LA - Winn Parish"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_129" value="504" literal="129">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Donley County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_13" value="527" literal="13">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="WA - Columbia County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_130" value="575" literal="130">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Ketchikan Gateway Borough"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_131" value="576" literal="131">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="FL - Walton County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_133" value="599" literal="133">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Eastland County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_135" value="622" literal="135">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Gwinnett County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_137" value="643" literal="137">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="SD - Ziebach County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_139" value="664" literal="139">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MI - Ottawa County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_14" value="684" literal="14">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="CO - Broomfield County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_141" value="685" literal="141">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Hancock County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_143" value="705" literal="143">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="OK - Tulsa County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_145" value="724" literal="145">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MN - Stearns County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_147" value="743" literal="147">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Fannin County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_149" value="762" literal="149">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MN - Stevens County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_15" value="781" literal="15">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ID - Boise County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_150" value="828" literal="150">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Kodiak Island Borough"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_151" value="829" literal="151">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="KY - Madison County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_153" value="846" literal="153">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="OK - Woodward County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_155" value="864" literal="155">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MS - Webster County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_157" value="880" literal="157">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Fort Bend County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_159" value="896" literal="159">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Franklin County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_16" value="912" literal="16">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Aleutians West Census Area"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_161" value="913" literal="161">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MI - Washtenaw County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_163" value="929" literal="163">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TN - Sullivan County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_164" value="945" literal="164">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Lake and Peninsula Borough"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_165" value="946" literal="165">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="IN - Vermillion County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_167" value="961" literal="167">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="IA - Sioux County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_169" value="975" literal="169">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="KY - Metcalfe County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_17" value="989" literal="17">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="LA - Caddo Parish"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_170" value="1035" literal="170">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Matanuska-Susitna Borough"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_171" value="1036" literal="171">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TN - Unicoi County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_173" value="1050" literal="173">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MO - Ralls County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_175" value="1064" literal="175">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Southampton County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_177" value="1077" literal="177">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Gonzales County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_179" value="1089" literal="179">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Stafford County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_180" value="1101" literal="180">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Nome Census Area"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_181" value="1102" literal="181">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="IL - Union County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_183" value="1114" literal="183">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="KY - Ohio County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_185" value="1126" literal="185">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="KS - Stafford County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_186" value="1138" literal="186">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MO - Ste. Genevieve County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_187" value="1139" literal="187">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TN - Williamson County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_188" value="1149" literal="188">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Northwest Arctic Borough"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_189" value="1150" literal="189">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="KY - Owsley County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_19" value="1159" literal="19">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="NY - Clinton County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_191" value="1205" literal="191">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="KS - Sumner County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_193" value="1213" literal="193">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Westmoreland County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_195" value="1221" literal="195">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MO - Saline County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_197" value="1231" literal="197">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="KY - Powell County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_198" value="1240" literal="198">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Prince of Wales-Hyder Census Area"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_199" value="1241" literal="199">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="IL - Williamson County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_20" value="1249" literal="20">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Anchorage Municipality"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_201" value="1252" literal="201">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Miller County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_203" value="1258" literal="203">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MO - Shannon County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_205" value="1263" literal="205">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MO - Shelby County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_207" value="1268" literal="207">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Haskell County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_209" value="1273" literal="209">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Hays County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_21" value="1278" literal="21">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MT - Dawson County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_211" value="1323" literal="211">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MO - Sullivan County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_213" value="1327" literal="213">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Henderson County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_215" value="1331" literal="215">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Muscogee County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_217" value="1335" literal="217">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Newton County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_219" value="1339" literal="219">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MO - Warren County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_220" value="1343" literal="220">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Sitka City and Borough"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_221" value="1344" literal="221">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Hood County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_223" value="1348" literal="223">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MO - Wayne County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_225" value="1352" literal="225">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MO - Webster County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_227" value="1356" literal="227">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="KY - Warren County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_229" value="1360" literal="229">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="KY - Washington County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_23" value="1364" literal="23">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="IN - Clinton County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_230" value="1409" literal="230">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Skagway Municipality"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_231" value="1410" literal="231">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Hunt County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_233" value="1413" literal="233">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Hutchinson County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_235" value="1416" literal="235">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="KY - Whitley County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_237" value="1419" literal="237">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="KY - Wolfe County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_239" value="1422" literal="239">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="KY - Woodford County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_240" value="1425" literal="240">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Southeast Fairbanks Census Area"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_241" value="1426" literal="241">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Jasper County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_243" value="1428" literal="243">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Randolph County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_245" value="1430" literal="245">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Richmond County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_247" value="1432" literal="247">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Rockdale County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_249" value="1434" literal="249">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Jim Wells County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_25" value="1436" literal="25">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AL - Clarke County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_251" value="1479" literal="251">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Screven County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_253" value="1481" literal="253">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Jones County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_255" value="1483" literal="255">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Karnes County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_257" value="1485" literal="257">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Kaufman County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_259" value="1487" literal="259">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Kendall County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_261" value="1489" literal="261">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Sumter County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_263" value="1492" literal="263">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Talbot County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_265" value="1494" literal="265">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Kerr County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_267" value="1496" literal="267">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Kimble County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_269" value="1498" literal="269">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - King County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_27" value="1500" literal="27">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="PA - Centre County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_270" value="1545" literal="270">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Wade Hampton Census Area"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_271" value="1546" literal="271">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Telfair County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_273" value="1548" literal="273">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Kleberg County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_275" value="1550" literal="275">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Thomas County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_277" value="1553" literal="277">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Lamar County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_279" value="1555" literal="279">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Toombs County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_28" value="1557" literal="28">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="NM - Los Alamos County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_281" value="1558" literal="281">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Lampasas County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_282" value="1560" literal="282">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Yakutat City and Borough"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_283" value="1561" literal="283">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Treutlen County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_285" value="1563" literal="285">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Lavaca County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_287" value="1565" literal="287">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Lee County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_289" value="1567" literal="289">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Leon County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_29" value="1569" literal="29">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="NC - Camden County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_290" value="1611" literal="290">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Yukon-Koyukuk Census Area"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_291" value="1612" literal="291">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Liberty County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_293" value="1614" literal="293">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Limestone County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_295" value="1616" literal="295">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Walker County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_297" value="1618" literal="297">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Walton County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_299" value="1620" literal="299">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Ware County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_3" value="1622" literal="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="CT - Hartford County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_30" value="1672" literal="30">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AS - Rose Island"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_300" value="1674" literal="300">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="UM - Midway Islands"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_301" value="1675" literal="301">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Loving County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_303" value="1677" literal="303">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Lubbock County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_305" value="1679" literal="305">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Lynn County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_307" value="1681" literal="307">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - McCulloch County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_309" value="1683" literal="309">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - McLennan County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_31" value="1685" literal="31">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="KS - Coffey County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_311" value="1727" literal="311">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - White County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_313" value="1729" literal="313">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Madison County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_315" value="1731" literal="315">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Marion County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_317" value="1733" literal="317">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Wilkes County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_319" value="1735" literal="319">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Mason County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_321" value="1737" literal="321">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Worth County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_323" value="1739" literal="323">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Maverick County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_325" value="1740" literal="325">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Medina County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_327" value="1741" literal="327">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Menard County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_329" value="1742" literal="329">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Midland County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_33" value="1743" literal="33">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Caroline County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_331" value="1784" literal="331">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Milam County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_333" value="1785" literal="333">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Mills County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_335" value="1786" literal="335">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Mitchell County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_337" value="1787" literal="337">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Montague County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_339" value="1788" literal="339">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Montgomery County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_341" value="1789" literal="341">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Moore County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_343" value="1790" literal="343">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Morris County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_345" value="1791" literal="345">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Motley County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_347" value="1792" literal="347">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Nacogdoches County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_349" value="1793" literal="349">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Navarro County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_35" value="1794" literal="35">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Butts County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_351" value="1834" literal="351">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Newton County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_353" value="1835" literal="353">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Nolan County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_355" value="1836" literal="355">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Nueces County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_357" value="1837" literal="357">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Ochiltree County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_359" value="1838" literal="359">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Oldham County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_36" value="1839" literal="36">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Charles City County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_361" value="1840" literal="361">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Orange County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_363" value="1841" literal="363">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Palo Pinto County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_365" value="1842" literal="365">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Panola County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_367" value="1843" literal="367">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Parker County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_369" value="1844" literal="369">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Parmer County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_37" value="1845" literal="37">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="IN - Dubois County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_371" value="1885" literal="371">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Pecos County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_373" value="1886" literal="373">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Polk County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_375" value="1887" literal="375">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Potter County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_377" value="1888" literal="377">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Presidio County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_379" value="1889" literal="379">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Rains County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_381" value="1890" literal="381">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Randall County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_383" value="1891" literal="383">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Reagan County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_385" value="1892" literal="385">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Real County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_387" value="1893" literal="387">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Red River County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_389" value="1894" literal="389">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Reeves County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_39" value="1895" literal="39">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AR - Dallas County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_391" value="1934" literal="391">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Refugio County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_393" value="1935" literal="393">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Roberts County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_395" value="1936" literal="395">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Robertson County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_397" value="1937" literal="397">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Rockwall County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_399" value="1938" literal="399">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Runnels County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_40" value="1939" literal="40">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AS - Swains Island"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_401" value="1940" literal="401">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Rusk County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_403" value="1941" literal="403">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Sabine County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_405" value="1942" literal="405">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - San Augustine County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_407" value="1943" literal="407">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - San Jacinto County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_409" value="1944" literal="409">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - San Patricio County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_41" value="1945" literal="41">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="WV - Lewis County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_411" value="1984" literal="411">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - San Saba County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_413" value="1985" literal="413">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Schleicher County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_415" value="1986" literal="415">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Scurry County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_417" value="1987" literal="417">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Shackelford County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_419" value="1988" literal="419">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Shelby County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_421" value="1989" literal="421">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Sherman County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_423" value="1990" literal="423">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Smith County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_425" value="1991" literal="425">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Somervell County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_427" value="1992" literal="427">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Starr County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_429" value="1993" literal="429">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Stephens County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_43" value="1994" literal="43">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="FL - Glades County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_431" value="2033" literal="431">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Sterling County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_433" value="2034" literal="433">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Stonewall County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_435" value="2035" literal="435">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Sutton County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_437" value="2036" literal="437">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Swisher County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_439" value="2037" literal="439">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Tarrant County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_441" value="2038" literal="441">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Taylor County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_443" value="2039" literal="443">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Terrell County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_445" value="2040" literal="445">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Terry County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_447" value="2041" literal="447">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Throckmorton County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_449" value="2042" literal="449">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Titus County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_45" value="2043" literal="45">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="IN - Fountain County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_451" value="2082" literal="451">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Tom Green County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_453" value="2083" literal="453">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Travis County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_455" value="2084" literal="455">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Trinity County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_457" value="2085" literal="457">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Tyler County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_459" value="2086" literal="459">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Upshur County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_461" value="2087" literal="461">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Upton County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_463" value="2088" literal="463">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Uvalde County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_465" value="2089" literal="465">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Val Verde County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_467" value="2090" literal="467">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Van Zandt County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_469" value="2091" literal="469">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Victoria County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_47" value="2092" literal="47">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="WV - McDowell County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_471" value="2130" literal="471">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Walker County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_473" value="2131" literal="473">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Waller County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_475" value="2132" literal="475">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Ward County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_477" value="2133" literal="477">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Washington County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_479" value="2134" literal="479">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Webb County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_481" value="2135" literal="481">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Wharton County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_483" value="2136" literal="483">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Wheeler County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_485" value="2137" literal="485">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Wichita County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_487" value="2138" literal="487">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Wilbarger County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_489" value="2139" literal="489">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Willacy County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_49" value="2140" literal="49">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Cumberland County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_491" value="2177" literal="491">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Williamson County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_493" value="2178" literal="493">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Wilson County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_495" value="2179" literal="495">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Winkler County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_497" value="2180" literal="497">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Wise County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_499" value="2181" literal="499">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Wood County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_5" value="2182" literal="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VT - Caledonia County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_50" value="2232" literal="50">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AS - Western District"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_501" value="2234" literal="501">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Yoakum County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_503" value="2235" literal="503">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Young County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_505" value="2236" literal="505">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Zapata County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_507" value="2237" literal="507">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TX - Zavala County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_51" value="2238" literal="51">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="UT - Wasatch County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_510" value="2275" literal="510">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MO - St. Louis city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_515" value="2279" literal="515">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Bedford city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_520" value="2280" literal="520">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Bristol city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_53" value="2281" literal="53">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GA - Chattahoochee County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_530" value="2318" literal="530">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Buena Vista city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_54" value="2319" literal="54">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="PR - Florida Municipio"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_540" value="2320" literal="540">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Charlottesville city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_55" value="2321" literal="55">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MI - Grand Traverse County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_550" value="2357" literal="550">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Chesapeake city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_57" value="2358" literal="57">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="FL - Hillsborough County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_570" value="2395" literal="570">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Colonial Heights city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_580" value="2396" literal="580">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Covington city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_59" value="2397" literal="59">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="KS - Franklin County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_590" value="2433" literal="590">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Danville city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_595" value="2434" literal="595">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Emporia city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_6" value="2435" literal="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="NM - Cibola County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_60" value="2436" literal="60">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Bristol Bay Borough"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_600" value="2437" literal="600">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Fairfax city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_61" value="2438" literal="61">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="KY - Edmonson County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_610" value="2474" literal="610">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Falls Church city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_620" value="2475" literal="620">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Franklin city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_63" value="2476" literal="63">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TN - Hamblen County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_630" value="2511" literal="630">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Fredericksburg city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_640" value="2512" literal="640">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Galax city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_65" value="2513" literal="65">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TN - Hamilton County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_650" value="2548" literal="650">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Hampton city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_660" value="2549" literal="660">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Harrisonburg city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_67" value="2550" literal="67">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MI - Ionia County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_670" value="2585" literal="670">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Hopewell city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_678" value="2586" literal="678">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Lexington city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_68" value="2587" literal="68">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Denali Borough"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_680" value="2588" literal="680">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Lynchburg city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_683" value="2589" literal="683">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Manassas city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_685" value="2590" literal="685">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Manassas Park city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_69" value="2591" literal="69">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ND - Pierce County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_690" value="2626" literal="690">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Martinsville city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_7" value="2627" literal="7">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="NM - Colfax County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_70" value="2675" literal="70">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Dillingham Census Area"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_700" value="2676" literal="700">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Newport News city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_71" value="2677" literal="71">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="IA - Fremont County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_710" value="2712" literal="710">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Norfolk city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_720" value="2713" literal="720">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Norton city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_73" value="2714" literal="73">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MO - Gasconade County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_730" value="2748" literal="730">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Petersburg city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_735" value="2749" literal="735">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Poquoson city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_740" value="2750" literal="740">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Portsmouth city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_75" value="2751" literal="75">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="IL - Iroquois County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_750" value="2785" literal="750">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Radford city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_760" value="2786" literal="760">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Richmond city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_77" value="2787" literal="77">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="WI - Marquette County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_770" value="2821" literal="770">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Roanoke city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_775" value="2822" literal="775">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Salem city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_78" value="2823" literal="78">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="WI - Menominee County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_79" value="2824" literal="79">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="WI - Milwaukee County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_790" value="2857" literal="790">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Staunton city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_800" value="2858" literal="800">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Suffolk city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_81" value="2859" literal="81">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MS - Lee County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_810" value="2892" literal="810">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Virginia Beach city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_820" value="2893" literal="820">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Waynesboro city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_83" value="2894" literal="83">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MT - Richland County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_830" value="2927" literal="830">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Williamsburg city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_840" value="2928" literal="840">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="VA - Winchester city"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_85" value="2929" literal="85">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="CA - Santa Clara County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_86" value="2963" literal="86">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="FL - Miami-Dade County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_87" value="2964" literal="87">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="OK - McClain County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_89" value="2997" literal="89">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="PA - Monroe County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_9" value="3029" literal="9">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="WV - Brooke County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_90" value="3078" literal="90">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="AK - Fairbanks North Star Borough"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_91" value="3079" literal="91">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="PA - Montgomery County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_93" value="3111" literal="93">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MS - Marshall County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_95" value="3142" literal="95">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MN - Mille Lacs County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_97" value="3173" literal="97">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="FL - Osceola County"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_99" value="3204" literal="99">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="SD - Minnehaha County"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="USCountyCodeSimpleTypeObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="USCountyCodeSimpleType:Object"/>
      <details key="baseType" value="USCountyCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="USCountyCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for US county codes."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="USCountyCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//USCountyCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
