<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="_0" nsURI="http://release.niem.gov/niem/codes/fips_5-2/3.0/"
    nsPrefix="_0">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Source: National Institute for Standards and Technology (NIST); &#xA;Publication: Codes for the Identification of the States, the District of Columbia, and the Outlying Areas of the U.S., and Associated Areas; &#xA;Date: 28 May 1987; &#xA;Source Updates: 1 Jan 1988; &#xA;http://www.itl.nist.gov/fipspubs/fip5-2.htm"/>
  </eAnnotations>
  <eAnnotations source="http://release.niem.gov/niem/conformanceTargets/3.0/">
    <details key="conformanceTargets" value="http://reference.niem.gov/niem/specification/naming-and-design-rules/3.0/#ReferenceSchemaDocument"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="USStateCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for state codes."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="USStateCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="AK">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Alaska"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="AL" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Alabama"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="AR" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Arkansas"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="AS" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="American Samoa"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="AZ" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Arizona"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CA" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="California"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CO" value="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Colorado"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CT" value="7">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Connecticut"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DC" value="8">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="District of Columbia"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DE" value="9">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Delaware"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FL" value="10">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Florida"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FM" value="11">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Federated States of Micronesia"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GA" value="12">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Georgia"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GU" value="13">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Guam"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="HI" value="14">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Hawaii"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="IA" value="15">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Iowa"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ID" value="16">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Idaho"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="IL" value="17">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Illinois"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="IN" value="18">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indiana"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="KS" value="19">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Kansas"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="KY" value="20">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Kentucky"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="LA" value="21">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Louisiana"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MA" value="22">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Massachusetts"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MD" value="23">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Maryland"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ME" value="24">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Maine"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MH" value="25">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Marshall Islands"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MI" value="26">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Michigan"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MN" value="27">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Minnesota"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MO" value="28">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Missouri"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MP" value="29">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Northern Mariana Islands"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MS" value="30">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Mississippi"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MT" value="31">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Montana"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NC" value="32">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="North Carolina"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ND" value="33">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="North Dakota"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NE" value="34">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Nebraska"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NH" value="35">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="New Hampshire"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NJ" value="36">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="New Jersey"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NM" value="37">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="New Mexico"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NV" value="38">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Nevada"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NY" value="39">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="New York"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="OH" value="40">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Ohio"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="OK" value="41">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Oklahoma"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="OR" value="42">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Oregon"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PA" value="43">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Pennsylvania"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PR" value="44">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Puerto Rico"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PW" value="45">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Palau"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="RI" value="46">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Rhode Island"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SC" value="47">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="South Carolina"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SD" value="48">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="South Dakota"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TN" value="49">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Tennessee"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TX" value="50">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Texas"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="UM" value="51">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Islands, Navassa Island, Palmyra Atoll, U.S. Minor Outlying Islands, Wake Island"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="UT" value="52">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Utah"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="VA" value="53">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Virginia"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="VI" value="54">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Virgin Islands of the U.S."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="VT" value="55">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Vermont"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="WA" value="56">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Washington"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="WI" value="57">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Wisconsin"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="WV" value="58">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="West Virginia"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="WY" value="59">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Wyoming"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="USStateCodeSimpleTypeObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="USStateCodeSimpleType:Object"/>
      <details key="baseType" value="USStateCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="USStateCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for state codes."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="USStateCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//USStateCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="USStateNumericCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for numeric state codes."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="USStateNumericCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="_01" literal="01">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Alabama"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_02" value="1" literal="02">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Alaska"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_04" value="2" literal="04">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Arizona"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_05" value="3" literal="05">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Arkansas"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_06" value="4" literal="06">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="California"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_08" value="5" literal="08">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Colorado"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_09" value="6" literal="09">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Connecticut"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_10" value="7" literal="10">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Delaware"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_11" value="8" literal="11">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="District of Columbia"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_12" value="9" literal="12">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Florida"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_13" value="10" literal="13">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Georgia"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_15" value="11" literal="15">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Hawaii"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_16" value="12" literal="16">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Idaho"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_17" value="13" literal="17">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Illinois"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_18" value="14" literal="18">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indiana"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_19" value="15" literal="19">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Iowa"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_20" value="16" literal="20">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Kansas"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_21" value="17" literal="21">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Kentucky"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_22" value="18" literal="22">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Louisiana"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_23" value="19" literal="23">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Maine"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_24" value="20" literal="24">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Maryland"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_25" value="21" literal="25">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Massachusetts"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_26" value="22" literal="26">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Michigan"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_27" value="23" literal="27">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Minnesota"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_28" value="24" literal="28">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Mississippi"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_29" value="25" literal="29">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Missouri"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_30" value="26" literal="30">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Montana"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_31" value="27" literal="31">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Nebraska"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_32" value="28" literal="32">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Nevada"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_33" value="29" literal="33">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="New Hampshire"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_34" value="30" literal="34">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="New Jersey"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_35" value="31" literal="35">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="New Mexico"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_36" value="32" literal="36">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="New York"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_37" value="33" literal="37">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="North Carolina"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_38" value="34" literal="38">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="North Dakota"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_39" value="35" literal="39">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Ohio"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_40" value="36" literal="40">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Oklahoma"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_41" value="37" literal="41">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Oregon"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_42" value="38" literal="42">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Pennsylvania"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_44" value="39" literal="44">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Rhode Island"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_45" value="40" literal="45">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="South Carolina"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_46" value="41" literal="46">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="South Dakota"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_47" value="42" literal="47">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Tennessee"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_48" value="43" literal="48">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Texas"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_49" value="44" literal="49">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Utah"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_50" value="45" literal="50">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Vermont"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_51" value="46" literal="51">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Virginia"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_53" value="47" literal="53">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Washington"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_54" value="48" literal="54">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="West Virginia"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_55" value="49" literal="55">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Wisconsin"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_56" value="50" literal="56">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Wyoming"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_60" value="51" literal="60">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="American Samoa"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_64" value="52" literal="64">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Federated States of Micronesia"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_66" value="53" literal="66">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Guam"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_67" value="54" literal="67">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Johnston Atoll"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_68" value="55" literal="68">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Marshall Islands"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_69" value="56" literal="69">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Northern Mariana Islands"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_70" value="57" literal="70">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Palau"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_71" value="58" literal="71">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Midway Islands"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_72" value="59" literal="72">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Puerto Rico"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_74" value="60" literal="74">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="U.S. Minor Outlying Islands"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_76" value="61" literal="76">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Navassa Island"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_78" value="62" literal="78">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Virgin Islands of the U.S."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_79" value="63" literal="79">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Wake Island"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_81" value="64" literal="81">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Baker Island"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_84" value="65" literal="84">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Howland Island"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_86" value="66" literal="86">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Jarvis Island"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_89" value="67" literal="89">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Kingman Reef"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_95" value="68" literal="95">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Palmyra Atoll"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="USStateNumericCodeSimpleTypeObject"
      instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="USStateNumericCodeSimpleType:Object"/>
      <details key="baseType" value="USStateNumericCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="USStateNumericCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for numeric state codes."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="USStateNumericCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//USStateNumericCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
