<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="_0" nsURI="http://release.niem.gov/niem/codes/core_misc/3.0/"
    nsPrefix="_0">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Non-authoritative codes for the direction of a person's pose in an image.&#xA;Source: NIEM 3.0; &#xA;Publication: NIEM 3.0; &#xA;Version: 3.0; &#xA;Date: Oct 2013;   &#xA;http://release.niem.gov/niem/3.0/"/>
  </eAnnotations>
  <eAnnotations>
    <details key="appinfo" value="&#xD;&#xA;      &lt;term:LocalTerm literal=&quot;Universal Transverse Mercator&quot; term=&quot;UTM&quot; xmlns:term=&quot;http://release.niem.gov/niem/localTerminology/3.0/&quot;/>&#xD;&#xA;    "/>
  </eAnnotations>
  <eAnnotations source="http://release.niem.gov/niem/conformanceTargets/3.0/">
    <details key="conformanceTargets" value="http://reference.niem.gov/niem/specification/naming-and-design-rules/3.0/#ReferenceSchemaDocument"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="ContactInformationAvailabilityCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for a period of time or a situation in which an entity is available to be contacted with the given contact information."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ContactInformationAvailabilityCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="day">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Daytime"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="emergency" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Emergency"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="evening" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Late day or early night"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="night" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Late night"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="primary" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Primary"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="secondary" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Secondary or alternate"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ContactInformationAvailabilityCodeSimpleTypeObject"
      instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ContactInformationAvailabilityCodeSimpleType:Object"/>
      <details key="baseType" value="ContactInformationAvailabilityCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContactInformationAvailabilityCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for a period of time or a situation in which an entity is available to be contacted with the given contact information."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ContactInformationAvailabilityCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//ContactInformationAvailabilityCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DayOfWeekCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for days of the week."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DayOfWeekCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="FRI">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Friday"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MON" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Monday"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SAT" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Saturday"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SUN" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Sunday"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="THU" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Thursday"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TUE" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Tuesday"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="WED" value="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Wednesday"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DayOfWeekCodeSimpleTypeObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DayOfWeekCodeSimpleType:Object"/>
      <details key="baseType" value="DayOfWeekCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DayOfWeekCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for days of the week."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DayOfWeekCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//DayOfWeekCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ImagePoseCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for angles of an entitys pose in a photograph."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ImagePoseCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="Frontal">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The object in the image is facing the front."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Oblique" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The object in the image is facing a quarter view."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Side" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The object in the image is facing the side."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ImagePoseCodeSimpleTypeObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ImagePoseCodeSimpleType:Object"/>
      <details key="baseType" value="ImagePoseCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImagePoseCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for angles of an entitys pose in a photograph."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ImagePoseCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//ImagePoseCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MilitaryDischargeCategoryCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for kinds of discharges a person may receive from military service."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="MilitaryDischargeCategoryCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="B">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="BAD CONDUCT"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="D" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="DISHONORABLE"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="G" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GENERAL"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="H" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="HONORABLE"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="M" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="MEDICAL"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="N" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="NOT APPLICABLE"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="O" value="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="OTHER"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Q" value="7">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="UNDESIRABLE"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="U" value="8">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="UNKNOWN"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="MilitaryDischargeCategoryCodeSimpleTypeObject"
      instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="MilitaryDischargeCategoryCodeSimpleType:Object"/>
      <details key="baseType" value="MilitaryDischargeCategoryCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MilitaryDischargeCategoryCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for kinds of discharges a person may receive from military service."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="MilitaryDischargeCategoryCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//MilitaryDischargeCategoryCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OffenseLevelCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for levels of an incident."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="OffenseLevelCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="F">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Felony"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="G" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Gross Misdemeanor"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="M" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Misdemeanor"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="P" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Petty Misdemeanor"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="OffenseLevelCodeSimpleTypeObject"
      instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="OffenseLevelCodeSimpleType:Object"/>
      <details key="baseType" value="OffenseLevelCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OffenseLevelCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for levels of an incident."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="OffenseLevelCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//OffenseLevelCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PersonNameCategoryCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for a kind of person name."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="PersonNameCategoryCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="Alternate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Alternate"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Asserted" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Asserted"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Legal" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Legal"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="PersonNameCategoryCodeSimpleTypeObject"
      instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="PersonNameCategoryCodeSimpleType:Object"/>
      <details key="baseType" value="PersonNameCategoryCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonNameCategoryCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for a kind of person name."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="PersonNameCategoryCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//PersonNameCategoryCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PleaCategoryCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for kinds of pleas."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="PleaCategoryCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="A">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="PLEA IN ABEYANCE"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="C" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="NO CONTEST"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="G" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GUILTY"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="I" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="N GUILTY/INSANITY"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="M" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="GUILTY/MENTAL ILL"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="N" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="NOT GUILTY"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="U" value="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="UNKNOWN"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="X" value="7">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="NO PLEA ENTERED"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="PleaCategoryCodeSimpleTypeObject"
      instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="PleaCategoryCodeSimpleType:Object"/>
      <details key="baseType" value="PleaCategoryCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PleaCategoryCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for kinds of pleas."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="PleaCategoryCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//PleaCategoryCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StatuteCategoryCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for kinds of statutes."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="StatuteCategoryCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="B">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Both C and P"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="C" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Charging"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="D" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Definition"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="J" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Juvenile Status/CHIP"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="N" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not Chargeable"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="P" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Penalty"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="StatuteCategoryCodeSimpleTypeObject"
      instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="StatuteCategoryCodeSimpleType:Object"/>
      <details key="baseType" value="StatuteCategoryCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatuteCategoryCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for kinds of statutes."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="StatuteCategoryCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//StatuteCategoryCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SupervisionLevelCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for levels of supervision required for a person."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SupervisionLevelCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="_1LOWRISK" literal="1-LOW RISK">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Low risk"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_2MODERATERISK" value="1" literal="2-MODERATE RISK">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Moderate risk"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_3HIGHRISK" value="2" literal="3-HIGH RISK">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="High risk"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_4EXTREMERISK" value="3" literal="4-EXTREME RISK">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Extreme risk"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="COMPACTOUT" value="4" literal="COMPACT OUT">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Compact out"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FUGITIVE" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Fugitive"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ISPI" value="6" literal="ISP I">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ISP I"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ISPII" value="7" literal="ISP II">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ISP II"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="RESIDINSTATECUSTD" value="8" literal="RESID/IN-STATE CUSTD">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="RESID/IN-STATE CUSTODY"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="SupervisionLevelCodeSimpleTypeObject"
      instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SupervisionLevelCodeSimpleType:Object"/>
      <details key="baseType" value="SupervisionLevelCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupervisionLevelCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for levels of supervision required for a person."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SupervisionLevelCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//SupervisionLevelCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SupervisionRestrictionCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for restrictions placed upon a person under supervision."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SupervisionRestrictionCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="ABSCONDING">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="I will not abscond from parole supervision.  A-Reporting: I will report as directed by the Utah Department of Corrections.  B-Residence: I will establish and reside at a residence of record and will not change my residence without first obtaining permission from my AP&amp;P Officer.  C-Leaving the State: I will not leave the state of Utah, even briefly, or any other state to which I am released or transferred without prior written permission from my AP&amp;P Officer."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ALCOHOL" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not consume any alcoholic beverages or have them under control or in my possession at any time."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ALCOHOLESTABLISHMNT" value="2" literal="ALCOHOL ESTABLISHMNT">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not enter any place where alcoholic beverages are being consumed or served as the chief item of order."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ARRESTCITATIONS" value="3" literal="ARREST-CITATIONS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Report any arrests or citations to Adult Probation and Parole within eight hours of occurrence."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ASSOCIATION" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not knowingly associate with any person who is involved in criminal activity or who has been convicted of a felony without approval from the AP&amp;P Officer."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CHEMICALANALYSIS" value="5" literal="CHEMICAL ANALYSIS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Abstain from the illegal use, possession, control, delivery, production, manufacture or distribution of controlled substances (58-37-2 U.C.A.) and submit to tests of breath or body fluids to ensure compliance with the Probation Agreement."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CHILDRENCONGREGATE" value="6" literal="CHILDREN CONGREGATE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not enter places or events where children congregate including, but not limited to:  schools, playgrounds, parks, arcades, parties, family functions, holiday festivities or any other place or function where children are present or reasonably expected to be present without prior written approval from Adult Probation and Parole or without the supervision of a responsible adult previously approved by Adult Probation and Parole."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CHILDRENUNDER18" value="7" literal="CHILDREN UNDER 18">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Have no contact or association with children under the age of 18 without prior written approval of Adult Probation and Parole."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CONDUCT" value="8">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="I will obey all state, federal and municipal laws.  I will submit DNA identifier as required by law.  If arrested, cited or questioned by a peace officer; I will notify my AP&amp;P Officer within 48 hours of the incident."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CURFEW" value="9">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Be at place of residence between the hours of the designated curfew times every day of the week unless otherwise approved by the supervising AP&amp;P Officer, and comply with the confinement schedule and the confinement area."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DISCONNECTPHONE" value="10" literal="DISCONNECT PHONE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not disconnect the telephone line, power cord, or tamper with the transmitter in any way without prior authorization from the supervising AP&amp;P Officer or the Electronic Monitoring Staff."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DNA" value="11">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Comply with Utah Code Annotated Section 53-10-403-406 by submitting an adequate DNA specimen, and, unless determination is made that there is no ability to pay, reimburse the responsible agency $75.00 for the cost of obtaining the specimen."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DOCUMENTSDATAPHOTO" value="12" literal="DOCUMENTS/DATA/PHOTO">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not have in my possession any written materials, documents, computer data, photographs which give evidence of gang involvement or activity such as: (1) membership or enemy lists, (2) articles which contain or have upon them gang-associated graffiti, drawings or lettering, (3) photographs or newspaper clippings of gang members, gang crimes or activities including obituaries, (4) photographs of myself in gang clothing, demonstrating hand signs or holding weapons."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DRIVERLICENSEID" value="13" literal="DRIVER LICENSE/ID">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Obtain and carry on my person at all times a valid Utah Driver License, Utah Identification Card or other approved photo identification."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DRUGS" value="14">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Abstain from the illegal use, possession, control, delivery, production, manufacture or distribution of marijuana, narcotics, controlled substances or other drugs as defined in the Controlled Substances Act, Utah Code Annotated 58-37-2 as amended."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ELECTRONICMONITOR" value="15" literal="ELECTRONIC MONITOR">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Participate in electronic surveillance when offense(s) occurred in the evening or nighttime hours."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="EMPLOYMENT" value="16">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Unless otherwise authorized by the AP&amp;P Officer; seek, obtain and maintain verifiable, lawful, full-time employment (32 hours per week minimum) as approved by the AP&amp;P Officer.  Notify the AP&amp;P Officer of any change in my employment within 48 hours of the change."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="EMPLOYMENTVERIFY" value="17" literal="EMPLOYMENT VERIFY">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Provide check stubs or other verification of employment to Adult Probation and Parole at least twice monthly."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ENTERTAINLURE" value="18" literal="ENTERTAIN/LURE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not have in my possession or under my control any items or materials either designed for, or used to, entertain, lure or attract the attention of children under the age of 18 without prior written approval from Adult Probation and Parole."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="EXPLOITMATERIAL" value="19" literal="EXPLOIT MATERIAL">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not have in my possession or under my control any material that describes or depicts human nudity, the exploitation of children, consensual sex acts, non-consensual sex acts, sexual acts involving force or violence including, but not limited to:  computer programs, computer links, photographs, drawings, video tapes, audio tapes, magazines, books, literature, writings, etc. without prior approval from Adult Probation and Parole."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FEES" value="20">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="I will pay supervision fees as determined by the Department of Corrections."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FINANCIALAGREEMENT" value="21" literal="FINANCIAL AGREEMENT">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Obtain permission from the supervising AP&amp;P Officer before entering into any financial agreement requiring installment payments."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FIREARMAMMUITION" value="22" literal="FIREARM/AMMUITION">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not have in my possession, in my custody, under my control, in a vehicle in which I am a passenger, or on the premises where I reside: (1) any firearm or replica thereof, (2) ammunition, or (3) dangerous weapon (any item which, in the manner of its use or intended use, is capable of causing death or serious bodily injury), and further, I shall not associate with, or be in the company of, any individual who has firearms or dangerous weapons in their possession or under their control."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FIREARMSUSED" value="23" literal="FIREARMS USED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not be involved in activities in which, or frequent places at which, firearms or dangerous weapons are used, legally or otherwise including, but not limited to, hunting or target shooting."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FREQUENTGANGPLACES" value="24" literal="FREQUENT GANG PLACES">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not frequent places where known gang members congregate."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FREQUENTSCHOOLS" value="25" literal="FREQUENT SCHOOLS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not visit or frequent any school ground unless I am a student registered at that school and present during appropriate class hours."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GANGMEMBERS" value="26" literal="GANG MEMBERS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not associate with any known gang member."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GEDDIPLOMA" value="27" literal="GED/DIPLOMA">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Earn a GED and/or high school diploma or complete vocational training or an apprentice program as directed."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="HMUABUSE" value="28" literal="HMU ABUSE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not physically abuse the electronic monitoring equipment; i.e. Home Monitoring Unit (HMU), transmitter or band.  If the HMU, transmitter or band is lost, damaged or tampered with; understand responsibility for the replacement and/or repair cost of the equipment."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="HMUMOVE" value="29" literal="HMU MOVE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not move the Home Monitoring Unit (HMU) without prior authorization from the supervising AP&amp;P Officer or the Electronic Monitoring Staff."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="HOMEVISITS" value="30" literal="HOME VISITS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="I will permit visits to my place of residence by officers of Adult Probation and Parole for the purpose of ensuring compliance with the conditions of my parole. I will not interfere with this requirement; i.e. having vicious dogs, perimeter security doors, refusing to open the door, etc."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="INSIGNIASEMBLEMS" value="31" literal="INSIGNIAS/EMBLEMS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not wear, display, use or possess any insignias, emblems or clothing associated with a specific gang(s) including, but not limited to: belt buckles, jewelry, caps/hats, jackets, shoes/shoe laces, scarves/bandanas, shirts inscribed &quot;In Memory Of&quot; a deceased or incarcerated gang member, or other articles of clothing modified to represent a particular gang(s)."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="INTERSTATECOMPACT" value="32" literal="INTERSTATE COMPACT">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Execute and adhere to the terms of the Interstate Compact Waiver and Agreement if probation or parole is served outside the state of Utah."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="LAWENFORCECONTACT" value="33" literal="LAW ENFORCE CONTACT">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If/when contacted by law enforcement, I shall provide my true name, place of residence (street address, not PO Box) and date of birth, and inform the officer(s) of my probation or parole status; I shall report such contact to my supervising agent within 48 hours, including the date and the nature of the contact, the law enforcement agency and any potential charges."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="LEAVECOUNTY" value="34" literal="LEAVE COUNTY">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not leave county of residence without prior authorization from Adult Probation and Parole."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MONTHLYPAYMENTS" value="35" literal="MONTHLY PAYMENTS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Make monthly payments toward any fine, restitution or supervision fees at a rate determined by the supervising AP&amp;P Officer."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NOALCOHOL" value="36" literal="NO ALCOHOL">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not consume, have in my possession or under my control alcoholic beverages, or frequent businesses where alcohol is the chief item of order."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NOCONTACTWVICTM" value="37" literal="NO CONTACT W/VICTM">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="No contact with the victim nor the victims family."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NOTATCOURT" value="38" literal="NOT AT COURT">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not appear in court or at a court building where other known gang member(s) are present and/or where a judicial proceeding involving a gang member is in progress, unless a party to proceedings in that court or subpoenaedto appear."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NOTDATE" value="39" literal="NOT DATE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not date persons with children residing at home under the age of 18 without prior written approval of Adult Probation and Parole."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PAGER" value="40">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not be in possession of any beeper or paging device, except in the course of lawful employment."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PAINTPENS" value="41" literal="PAINT/PENS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not have in my possession or under my control spray paint, spray can tips, large marking pens or other items commonly used to create graffiti, or tagger magazines."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PHONESERVICES" value="42" literal="PHONE SERVICES">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Understand the phone line may not have Call Waiting, Call Forwarding, Voice Mail or Caller ID; nor an answering machine, cordless phone, fax machine, computer modem or cellular phone used on the phone line.  Bring copies of phone bill to the supervising agent on a monthly basis for verification if needed."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="POLYGRAPH" value="43">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Submit to random polygraph examinations."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PORNOGRAPHY" value="44">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not view nor have in possession any pornographic material or material exploiting children or depicting unconsensual sex acts or acts involving force or violence."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PROVIDEPHONELINE" value="45" literal="PROVIDE PHONE LINE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Understand the Electronic Monitoring Program requires provision, at personal expense, of a phone line for the use of the HMU.  Understand the HMU may cause some disturbance with existing phone line."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="REGISTRATIONDNA" value="46" literal="REGISTRATION/DNA">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Comply with the requirements of Utah Sex Offender Registration and DNA specimen requirements."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="RELEASE" value="47">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="On the day of my release from the institution of confinement, I will report to my assigned AP&amp;P Officer unless otherwise approved in writing from Adult Probation and Parole."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="REPORTING" value="48">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not abscond from probation supervision.  A-Reporting: Report as directed by the Department of Corrections.  B-Residence: Establish and reside at a residence of record and not change residence without first obtaining permission from the AP&amp;P Officer.  C-Leaving the State: Not leave the state of Utah, even briefly, or any other state to which I am released or transferred without prior written permission from the AP&amp;P Officer."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="RESIDENCE" value="49">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Residence and residence changes must be approved by Adult Probation and Parole."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SEARCHES" value="50">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="I will permit officers of Adult Probation and Parole to search my person, residence, vehicle or any other property under my control without a warrant at any time, day or night, upon reasonable suspicion to ensure compliance with conditions of my parole."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SEXSTIMULUSMATERIA" value="51" literal="SEX STIMULUS MATERIA">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not have in my possession or under my control any material that acts as a sexual stimulus for my particular deviancy(s) including, but not limited to:  computer programs, computer links, photographs, drawings, video tapes, audio tapes, magazines, books, literature, writings, etc. without the written approval from Adult Probation and Parole."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SIGNSGESTURES" value="52" literal="SIGNS/GESTURES">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not display any gang signs, gestures or any posturing associated with any specific gang(s)."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SPECIAL" value="53">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Abide by the following special conditions as ordered by the Board of Pardons.  (enter special conditions)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="STOLENVEHICLE" value="54" literal="STOLEN VEHICLE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not be an occupant in any stolen vehicle, or vehicle I should have known was stolen."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SUBSTANCETESTING" value="55" literal="SUBSTANCE TESTING">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Agree to submit to urinalysis or other tests for marijuana, narcotics, controlled substances, alcohol or other drugs upon reasonable suspicion as ascertained by, and at the request of, any AP&amp;P Officer to ensure compliance with the conditions of the Intensive Supervision Program."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SUPERVISIONFEE" value="56" literal="SUPERVISION FEE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Agree to pay a supervision fee of $30 per month unless granted a waiver by the Department of Corrections under the provisions of Utah Statute 64-13-21."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="THERAPY" value="57">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Enter into, participate in and successfully complete sex offender therapy as determined by the treating facility, therapists and the Utah Department of Corrections."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TREATMENTCOUNSELING" value="58" literal="TREATMENT/COUNSELING">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Enter into, participate in and complete treatment, counseling or therapy as directed."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TRUTHFULNESS" value="59">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="I will be cooperative, compliant and truthful in all my dealings with Adult Probation and Parole.  If arrested, cited or questioned by a peace officer; notify the AP&amp;P Officer within 48 hours."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="UNEMPLOYED" value="60">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If unemployed, may be ordered to report to an assigned work project on Monday, Wednesday and Friday at 8 am.  Understand that this is work for which no compensation will be received.  Work on this assigned work project from 8 am to 5 pm or until dismissed by the project supervisor or the supervising agent.  on Tuesday and Thursday, report to the Adult Probation and Parole Office at 8 am with a list of potential employers; then go into the community and look for work.  Make a list of the places visited during the day."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="VEHICLE" value="61">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not operate any vehicle other than those reported to Adult Probation and Parole."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="VICIOUSDOGS" value="62" literal="VICIOUS DOGS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not own, possess, maintain or raise vicious dogs, nor keep them on the premises where I reside."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="VICTIMCONTACT" value="63" literal="VICTIM CONTACT">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Have no direct or indirect contact with the victim(s) or victims family without prior written approval from Adult Probation and Parole."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="VISITS" value="64">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Permit visits to my place of residence, my place of employment or elsewhere by officers of Adult Probation and Parole for the purpose of ensuring compliance with the conditions of the Probation Agreement."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="WEAPONS" value="65">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Not possess, have under control, have in my custody or on the premises where residing any explosives, firearmsor dangerous weapons.  (Dangerous weapon is defined as any item that in the manner of its use or intended use is capable of causing death or serious bodily injury.)  Exceptions to this condition may be made by the supervising agent and must be in writing.  This waiver will only apply to individuals on probation for a misdemeanor and who have never been convicted of a felony."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="SupervisionRestrictionCodeSimpleTypeObject"
      instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SupervisionRestrictionCodeSimpleType:Object"/>
      <details key="baseType" value="SupervisionRestrictionCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupervisionRestrictionCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for restrictions placed upon a person under supervision."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SupervisionRestrictionCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//SupervisionRestrictionCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UTMHemisphereCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for a hemisphere designation for a UTM coordinate."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="UTMHemisphereCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="N">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Northern hemisphere"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="S" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Southern hemisphere"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="UTMHemisphereCodeSimpleTypeObject"
      instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="UTMHemisphereCodeSimpleType:Object"/>
      <details key="baseType" value="UTMHemisphereCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UTMHemisphereCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for a hemisphere designation for a UTM coordinate."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="UTMHemisphereCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//UTMHemisphereCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
