<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="_0" nsURI="http://release.niem.gov/niem/codes/unece_rec20/3.0/"
    nsPrefix="_0">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Miscellaneous unit of measure codes.&#xA;Source: UN Economic Commission for Europe (UNECE); &#xA;Publication: UNECE Recommendation No. 20 Revision 8; &#xA;Version: Revision 8; &#xA;Date: 2012; &#xA;http://www.unece.org/tradewelcome/areas-of-work/un-centre-for-trade-facilitation-and-e-business-uncefact/outputs/cefactrecommendationsrec-index/list-of-trade-facilitation-recommendations-n-16-to-20.html"/>
  </eAnnotations>
  <eAnnotations source="http://release.niem.gov/niem/conformanceTargets/3.0/">
    <details key="conformanceTargets" value="http://reference.niem.gov/niem/specification/naming-and-design-rules/3.0/#ReferenceSchemaDocument"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="LengthCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for units of measurements for a length value."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="LengthCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="_4H" literal="4H">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="micrometre (micron)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_77" value="1" literal="77">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="milli-inch"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="A11" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="angstrom"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="A12" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="astronomical unit"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="A45" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="decametre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="A71" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="femtometre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="AK" value="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="fathom"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="B57" value="7">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="light year"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="C45" value="8">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="nanometre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="C52" value="9">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="picometre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="C63" value="10">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="parsec"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CMT" value="11">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="centimetre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DMT" value="12">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="decimetre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FOT" value="13">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="foot"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="HMT" value="14">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="hectometre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="INH" value="15">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="inch"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="KMT" value="16">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="kilometre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="M7" value="17">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="micro-inch"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MMT" value="18">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="millimetre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MTR" value="19">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="metre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NMI" value="20">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="nautical mile"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SMI" value="21">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="mile (statute mile)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="X1" value="22">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Gunter's chain"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="YRD" value="23">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="yard"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="LengthCodeSimpleTypeObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="LengthCodeSimpleType:Object"/>
      <details key="baseType" value="LengthCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LengthCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for units of measurements for a length value."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="LengthCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//LengthCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MassCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for units of measurement for a weight value."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="MassCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="_2U" literal="2U">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="megagram"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="APZ" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="troy ounce or apothecary ounce"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CGM" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="centigram"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CWA" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="hundred pounds (cwt) / hundred weight (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CWI" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="hundred weight (UK)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DG" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="decigram"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DJ" value="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="decagram"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DTN" value="7">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="decitonne"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GRM" value="8">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="gram"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GRN" value="9">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="grain"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="HGM" value="10">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="hectogram"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="KGM" value="11">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="kilogram"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="KTN" value="12">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="kilotonne"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="LBR" value="13">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="pound"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="LTN" value="14">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ton (UK) or long ton (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MC" value="15">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="microgram"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MGM" value="16">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="milligram"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ONZ" value="17">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ounce (avoirdupois)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="STI" value="18">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="stone (UK)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="STN" value="19">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ton (US) or short ton (UK/US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TNE" value="20">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="tonne (metric ton)"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="MassCodeSimpleTypeObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="MassCodeSimpleType:Object"/>
      <details key="baseType" value="MassCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MassCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for units of measurement for a weight value."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="MassCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//MassCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TemperatureUnitCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for temperature unit of measurement codes."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="TemperatureUnitCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="A48">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Rankine"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CEL" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Celsius"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="E98" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Celsius per kelvin"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="F02" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="kelvin per kelvin"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="F10" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="kelvin per hour"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="F11" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="kelvin per minute"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="F12" value="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="kelvin per second"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="F60" value="7">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Celsius per bar"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="F61" value="8">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="kelvin per bar"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FAH" value="9">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Fahrenheit"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="H12" value="10">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Celsius per hour"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="H13" value="11">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Celsius per minute"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="H14" value="12">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Celsius per second"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="J20" value="13">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Fahrenheit per kelvin"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="J21" value="14">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Fahrenheit per bar"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="J23" value="15">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Fahrenheit per hour"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="J24" value="16">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Fahrenheit per minute"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="J25" value="17">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Fahrenheit per second"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="J26" value="18">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="reciprocal degree Fahrenheit"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="J28" value="19">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Rankine per hour"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="J29" value="20">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Rankine per minute"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="J30" value="21">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="degree Rankine per second"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="N79" value="22">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="kelvin per pascal"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="TemperatureUnitCodeSimpleTypeObject"
      instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="TemperatureUnitCodeSimpleType:Object"/>
      <details key="baseType" value="TemperatureUnitCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemperatureUnitCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for temperature unit of measurement codes."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="TemperatureUnitCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//TemperatureUnitCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for units of time."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="TimeCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="ANN">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="year"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="B52" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="kilosecond"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="B98" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="microsecond"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="C26" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="millisecond"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="C47" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="nanosecond"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="D42" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="tropical year"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DAY" value="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="day"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="HUR" value="7">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="hour"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MIN" value="8">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="minute [unit of time]"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MON" value="9">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="month"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SEC" value="10">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="second [unit of time]"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="WEE" value="11">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="week"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="TimeCodeSimpleTypeObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="TimeCodeSimpleType:Object"/>
      <details key="baseType" value="TimeCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for units of time."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="TimeCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//TimeCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VelocityCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for units of measurement for a speed or velocity."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="VelocityCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="_2M" literal="2M">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="centimetre per second"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_2X" value="1" literal="2X">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="metre per minute"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="C16" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="millimetre per second"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FR" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="foot per minute"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FS" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="foot per second"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="HM" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="mile per hour (statute mile)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="IU" value="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="inch per second"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="KMH" value="7">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="kilometre per hour"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="KNT" value="8">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="knot"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MTS" value="9">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="metre per second"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="VelocityCodeSimpleTypeObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="VelocityCodeSimpleType:Object"/>
      <details key="baseType" value="VelocityCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VelocityCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for units of measurement for a speed or velocity."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="VelocityCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//VelocityCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VolumeUnitCodeSimpleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for volume unit of measurement codes."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="VolumeUnitCodeSimpleType"/>
    </eAnnotations>
    <eLiterals name="_4G" literal="4G">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="microlitre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="_5I" value="1" literal="5I">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="standard cubic foot"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="A44" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="decalitre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="BLD" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="dry barrel (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="BLL" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="barrel (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="BUA" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="bushel (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="BUI" value="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="bushel (UK)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CLT" value="7">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="centilitre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CMQ" value="8">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic centimetre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DLT" value="9">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="decilitre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DMA" value="10">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic decametre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DMQ" value="11">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic decimetre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FTQ" value="12">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic foot"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="G21" value="13">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cup [unit of volume]"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="G23" value="14">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="peck"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="G24" value="15">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="tablespoon (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="G25" value="16">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="teaspoon (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="G26" value="17">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="stere"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="G94" value="18">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic centimetre per bar"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="G95" value="19">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="litre per bar"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="G96" value="20">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic metre per bar"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="G97" value="21">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="millilitre per bar"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GLD" value="22">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="dry gallon (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GLI" value="23">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="gallon (UK)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GLL" value="24">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="gallon (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="H19" value="25">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic hectometre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="H20" value="26">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic kilometre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="HLT" value="27">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="hectolitre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="INQ" value="28">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic inch"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="J57" value="29">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="barrel (UK petroleum)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="K21" value="30">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic foot per degree Fahrenheit"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="K23" value="31">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic foot per psi"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="K6" value="32">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="kilolitre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="L43" value="33">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="peck (UK)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="L61" value="34">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="pint (US dry)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="L62" value="35">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="quart (US dry)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="L84" value="36">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ton (UK shipping)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="L86" value="37">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ton (US shipping)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="LTR" value="38">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="litre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="M11" value="39">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic yard per degree Fahrenheit"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="M14" value="40">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic yard per psi"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="M67" value="41">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="acre-foot (based on U.S. survey foot)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="M68" value="42">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cord (128 ft3)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="M69" value="43">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic mile (UK statute)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="M70" value="44">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ton, register"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="M71" value="45">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic metre per pascal"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MAL" value="46">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="megalitre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MLT" value="47">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="millilitre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MMQ" value="48">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic millimetre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MTQ" value="49">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic metre"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="OZA" value="50">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="fluid ounce (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="OZI" value="51">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="fluid ounce (UK)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PT" value="52">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="pint (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PTD" value="53">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="dry pint (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PTI" value="54">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="pint (UK)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PTL" value="55">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="liquid pint (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="QT" value="56">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="quart (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="QTD" value="57">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="dry quart (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="QTI" value="58">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="quart (UK)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="QTL" value="59">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="liquid quart (US)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="YDQ" value="60">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="cubic yard"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="VolumeUnitCodeSimpleTypeObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="VolumeUnitCodeSimpleType:Object"/>
      <details key="baseType" value="VolumeUnitCodeSimpleType"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VolumeUnitCodeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type for volume unit of measurement codes."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="VolumeUnitCodeType"/>
      <details key="kind" value="simple"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//VolumeUnitCodeSimpleType"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=":0"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="metadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREF">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipMetadata" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IDREFS">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="relationshipMetadata"/>
        <details key="namespace" value="http://release.niem.gov/niem/structures/3.0/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="urn:us:gov:ic:ism urn:us:gov:ic:ntk"/>
        <details key="name" value=":5"/>
        <details key="processing" value="lax"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
